"""added munnar location

Revision ID: 699f50d4feb9
Revises: 7ea63702bf7f
Create Date: 2025-02-16 17:00:04.393855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '699f50d4feb9'
down_revision: Union[str, None] = '7ea63702bf7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('specific_location', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotels', 'specific_location')
    # ### end Alembic commands ###
