"""refactor location htoel

Revision ID: 7ea63702bf7f
Revises: 269c3fe6245c
Create Date: 2025-02-16 15:42:18.607378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ea63702bf7f'
down_revision: Union[str, None] = '269c3fe6245c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('hotel_id', sa.String(), nullable=True))
    op.alter_column('hotels', 'location',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.add_column('wallet_transactions', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallet_transactions', 'date')
    op.alter_column('hotels', 'location',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('hotels', 'hotel_id')
    # ### end Alembic commands ###
