"""added munnar location -1

Revision ID: 7eb6829b75c9
Revises: 699f50d4feb9
Create Date: 2025-02-16 20:23:04.176430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7eb6829b75c9'
down_revision: Union[str, None] = '699f50d4feb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('name', sa.String(), nullable=True))
    op.add_column('activities', sa.Column('isBookable', sa.Boolean(), nullable=True))
    op.drop_column('activities', 'time')
    op.drop_column('activities', 'duration')
    op.drop_column('activities', 'booking_url')
    op.drop_column('activities', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('category', postgresql.ENUM('sightseeing', 'food', 'culture', 'adventure', 'relaxation', name='activity_categories'), autoincrement=False, nullable=True))
    op.add_column('activities', sa.Column('booking_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('activities', sa.Column('duration', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('activities', sa.Column('time', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('activities', 'isBookable')
    op.drop_column('activities', 'name')
    # ### end Alembic commands ###
