"""corrected error

Revision ID: 7c45512e62fb
Revises: a9b6d6132bc1
Create Date: 2025-02-16 14:06:55.995734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c45512e62fb'
down_revision: Union[str, None] = 'a9b6d6132bc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('coins', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallets', 'coins')
    # ### end Alembic commands ###
