"""Post for forum added

Revision ID: 8c9c24305a2c
Revises: 
Create Date: 2025-02-15 17:59:34.919153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c9c24305a2c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('activities_itinerary_item_id_fkey', 'activities', type_='foreignkey')
    op.drop_constraint('activities_trip_id_fkey', 'activities', type_='foreignkey')
    op.drop_column('activities', 'trip_id')
    op.drop_column('activities', 'itinerary_item_id')
    op.drop_constraint('hotels_trip_id_fkey', 'hotels', type_='foreignkey')
    op.drop_constraint('hotels_itinerary_item_id_fkey', 'hotels', type_='foreignkey')
    op.drop_column('hotels', 'trip_id')
    op.drop_column('hotels', 'itinerary_item_id')
    op.drop_constraint('sights_itinerary_item_id_fkey', 'sights', type_='foreignkey')
    op.drop_column('sights', 'itinerary_item_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sights', sa.Column('itinerary_item_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('sights_itinerary_item_id_fkey', 'sights', 'itinerary_items', ['itinerary_item_id'], ['id'])
    op.add_column('hotels', sa.Column('itinerary_item_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('hotels', sa.Column('trip_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('hotels_itinerary_item_id_fkey', 'hotels', 'itinerary_items', ['itinerary_item_id'], ['id'])
    op.create_foreign_key('hotels_trip_id_fkey', 'hotels', 'trips', ['trip_id'], ['id'])
    op.add_column('activities', sa.Column('itinerary_item_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('activities', sa.Column('trip_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('activities_trip_id_fkey', 'activities', 'trips', ['trip_id'], ['id'])
    op.create_foreign_key('activities_itinerary_item_id_fkey', 'activities', 'itinerary_items', ['itinerary_item_id'], ['id'])
    # ### end Alembic commands ###
